#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'active_record'
require 'yaml'
require 'logger'


APP_ROOT = File.join(File.dirname(File.expand_path(__FILE__)), '..')
ActiveRecord::Base.logger = Logger.new(File.join(APP_ROOT, 'log', 'build.log'))

require File.join(APP_ROOT, 'app/models/project')
require File.join(APP_ROOT, 'app/models/build')
require File.join(APP_ROOT, 'lib/cmd_line')

db_config = YAML::load(File.open(File.join(APP_ROOT, 'config/database.yml')))['development']
db_config['database'] = File.join(APP_ROOT, db_config['database'])
ActiveRecord::Base.establish_connection(db_config)

puts "Cloning repositories..."
Project.all.each {|project|project.prepare}

puts "Starting Sanity..."
loop do
  Project.all.each {|project|project.check}
  sleep(360)
end

