#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'lib/build'

Daemons.run_proc('build_runner') do

  build = Build.new('/home/phil/github/wheel2')

  loop do
    build.run
    sleep(30)
  end
end

